# Generated by Django 5.1.6 on 2025-02-25 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_brand_created_alter_category_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbase',
            name='is_featured',
        ),
    ]
